### ISSUE TITLE
Client Crash upon opening Stall

### ISSUE THREAD

**Issue by Mad-Gnome** [kenigvovan/CANMarket#3]
VS: 1.19.5
CAN Market: 0.3.24

Steps taken to recreate:
Vanilla Chest, Warehouse on it, Stall 2 blocks out.  Signed book from warehouse, placed into stall.
Object placed in vanilla chest, object set for sale in stall, price set.
I run the /canmarket cn Admin command.  I can buy from it fine and rusty gears are deducted.

All normal stuff.

I set infinite stocks to on, and store payment to no.  Once I re-open the stall I have a client side crash every single time I open the stall.
[client-crash.txt](https://github.com/kenigvovan/CANMarket/files/14764978/client-crash.txt)
[client-main.txt](https://github.com/kenigvovan/CANMarket/files/14764979/client-main.txt)

**Comment by kenigvovan** [comment]
try 0.3.25,
 I  placed clutter block to sale slot and all other settings but didn't get any exception yet

**Comment by Mad-Gnome** [comment]
I was testing it with a chunk of crystalized copper in the sale slot, with a vanilla chest under the warehouse block.

With 0.3.25:
I have Copper Lanterns for sale to test this time (vanilla chest under warehouse block again)

It lets me 'not store payment', and buy from the shop fine.
I click Infinite stock, fine.
Once I enter the stall again (interact with, open it, etc) it causes a client crash.

From the Audit-Log: 27.3.2024 12:36:54 [Audit] Client MadGnome got removed: 'Threw an exception at the server' (An action you (or your client) did caused an unhandled exception)
[server-main.txt](https://github.com/kenigvovan/CANMarket/files/14779988/server-main.txt)
[server-event.txt](https://github.com/kenigvovan/CANMarket/files/14779990/server-event.txt)

**Comment by kenigvovan** [comment]
fixed in 0.3.26
