### ISSUE TITLE
Client Crash after going through TL, client cannot load into server afterwards.

### ISSUE THREAD

**Issue by Mad-Gnome** [kenigvovan/CANMarket#4]
VS: 1.19.5
CAN Market: 0.3.27

One player on my server went though a TL, and had a client side crash.  Server-main just says client crashed.

Client-main and client-crash (based on my limited understanding of reading these) points to an issue with CAN Market.
[client-crash(2).txt](https://github.com/kenigvovan/CANMarket/files/14828428/client-crash.2.txt)
[client-main(1).txt](https://github.com/kenigvovan/CANMarket/files/14828429/client-main.1.txt)

**Comment by kenigvovan** [comment]
fixed in 0.3.28 (missing config on client side)
